version: '2'
    squid-proxy:
        image: lukasojd/squid-proxy:latest
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - /srv/docker/squid/cache:/var/spool/squid3
        ports:
          - "3128:3128"

    adminer_com:
      image: clue/adminer
      environment:
        - VIRTUAL_HOST=adminer.com

    adminer_eu:
        image: clue/adminer
        environment:
          - VIRTUAL_HOST=adminer.eu